version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: social_db
    ports:
      - "5432:5432"
  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"

  neo4j:
    image: neo4j
    container_name: neo4j_db
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"